#!/bin/sh

docker build \
  --build-arg proxy=1 \
  --build-arg http_proxy="http://172.17.0.1:3128" \
  --build-arg https_proxy="http://172.17.0.1:3128" \
  -t gadicc/diffusers-api-base:python3.9-pytorch1.12.1-cuda11.6-xformers \
  --build-arg FROM_IMAGE="continuumio/miniconda3:4.12.0" \
  .

docker build \
  --build-arg proxy=1 \
  --build-arg http_proxy="http://172.17.0.1:3128" \
  --build-arg https_proxy="http://172.17.0.1:3128" \
  -t gadicc/diffusers-api-base:python3.9-pytorch1.12.1-cuda11.6-xformers-banana \
  --build-arg FROM_IMAGE="pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime" \
  .

